"""cria tabela registro_jogadas

Revision ID: 1d37ff848fa3
Revises: 3371e7c4b1a2
Create Date: 2025-05-23 18:21:22.255280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d37ff848fa3'
down_revision = '3371e7c4b1a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registro_jogadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('resultado', sa.Enum('ganhou', 'perder', name='resultado_enum'), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cpf'], ['jogadores.cpf'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro_jogadas')
    # ### end Alembic commands ###
